#Application Configuration
spring.application.name=content-management-service
spring.config.import=optional:file:.env[.properties]
#spring.main.banner-mode=off
spring.output.ansi.enabled=ALWAYS
server.port=8082


#Http Configuration
spring.mvc.apiversion.use.header=X-API-Version
#app.cors.allowed-origins=${CORS}


#Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.connectionTimeout=${CONN_TIMEOUT}
spring.datasource.hikari.maximumPoolSize=${POOL_MAXSIZE}


#Security Configuration
#spring.security.user.name=${SEC_USERNAME}
#spring.security.user.password=${SEC_PASSWORD}
#logging.level.org.springframework.security=DEBUG


#JWT Configuration
#jwt.secret=${JWT_SECRET}
#jwt.expiration=${JWT_EXPIRATION}

# --- AWS INTEGRATION ---
cloud.aws.accessKey=${CLOUD_ACCESSKEY}
cloud.aws.secretKey=${CLOUD_SECRETKEY}
cloud.aws.region=${CLOUD_REGION}
cloud.aws.keypair=${KEY_PAIR}
aws.game-bucket.name=${GAME_BUCKET}
aws.image-bucket.name=${IMG_BUCKET}